# Introduction

Taking account of finds in 01_eda notebook, this sheet focusses on removing null values by using and engineered features.

# loading original dataset

In [24]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

!pip install -U scikit-learn

!pip install --upgrade pip


import sklearn

from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

Requirement already satisfied: scikit-learn in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: pip in /home/ram-gurung/miniconda3/lib/python3.13/site-packages (26.2.1)

In [4]:
# importing the file

df = pd.read_csv("/home/ram-gurung/Documents/projects/predictive_maintenance_edge/predictive_maintenance_edge/data/raw/predictive-maintenance-dataset.csv"
, low_memory=False) # to keep the memory usage low while importing the file.

,ID,revolutions,humidity,vibration,x1,x2,x3,x4,x5
0,1,93.744,73.999,18.00,167.743,19.745,1.266828,8787.937536,5475.852001
1,2,93.740,73.999,18.00,167.739,19.741,1.266774,8787.187600,5475.852001
2,3,93.736,73.998,18.00,167.734,19.738,1.266737,8786.437696,5475.704004
3,4,93.732,73.998,18.00,167.730,19.734,1.266683,8785.687824,5475.704004
4,5,93.729,73.998,18.00,167.727,19.731,1.266642,8785.125441,5475.704004
...,...,...,...,...,...,...,...,...,...
111996,111997,20.186,73.992,2.00,94.178,-53.806,0.272813,407.474596,5474.816064
111997,111998,20.186,73.992,20.01,94.178,-53.806,0.272813,407.474596,5474.816064
111998,111999,20.185,73.992,20.01,94.177,-53.807,0.272800,407.434225,5474.816064
111999,112000,20.185,73.992,20.00,94.177,-53.807,0.272800,407.434225,5474.816064
112000,112001,20.184,73.992,2.00,94.176,-53.808,0.272786,407.393856,5474.816064

In [5]:
# keeping the raw file intact and creating a copy

df_raw = df.copy()

df_raw

,ID,revolutions,humidity,vibration,x1,x2,x3,x4,x5
0,1,93.744,73.999,18.00,167.743,19.745,1.266828,8787.937536,5475.852001
1,2,93.740,73.999,18.00,167.739,19.741,1.266774,8787.187600,5475.852001
2,3,93.736,73.998,18.00,167.734,19.738,1.266737,8786.437696,5475.704004
3,4,93.732,73.998,18.00,167.730,19.734,1.266683,8785.687824,5475.704004
4,5,93.729,73.998,18.00,167.727,19.731,1.266642,8785.125441,5475.704004
...,...,...,...,...,...,...,...,...,...
111996,111997,20.186,73.992,2.00,94.178,-53.806,0.272813,407.474596,5474.816064
111997,111998,20.186,73.992,20.01,94.178,-53.806,0.272813,407.474596,5474.816064
111998,111999,20.185,73.992,20.01,94.177,-53.807,0.272800,407.434225,5474.816064
111999,112000,20.185,73.992,20.00,94.177,-53.807,0.272800,407.434225,5474.816064
112000,112001,20.184,73.992,2.00,94.176,-53.808,0.272786,407.393856,5474.816064

# Working on df

In [6]:
# for shape of dataframe

df.shape

(112001, 9)

In [10]:
# basic validation

print("The shape of dataframe is:", df.shape)
print("=========================")
print(df.dtypes)
print("=========================")
print(df.isnull().sum())
print("=========================")
print("Duplicate rows:", 
      df.duplicated().sum()
     )
print("=========================")
print("Duplicated IDs:", 
      df["ID"].duplicated().sum()
      )

The shape of dataframe is: (112001, 9)
=========================
ID               int64
revolutions    float64
humidity       float64
vibration      float64
x1             float64
x2             float64
x3             float64
x4             float64
x5             float64
dtype: object
=========================
ID                0
revolutions       0
humidity          0
vibration      2438
x1                0
x2                0
x3                0
x4                0
x5                0
dtype: int64
=========================
Duplicate rows: 0
=========================
Duplicated IDs: 0

In [13]:
# for analysis purpose taking only excluding x1, x2, x3, x4, x5

df1 = df[["revolutions", "humidity", "vibration"]]

In [14]:
df1

        revolutions  humidity  vibration
0            93.744    73.999      18.00
1            93.740    73.999      18.00
2            93.736    73.998      18.00
3            93.732    73.998      18.00
4            93.729    73.998      18.00
...             ...       ...        ...
111996       20.186    73.992       2.00
111997       20.186    73.992      20.01
111998       20.185    73.992      20.01
111999       20.185    73.992      20.00
112000       20.184    73.992       2.00

[112001 rows x 3 columns]

In [25]:
import sklearn

In [43]:
# 2. Keep required columns and remove missing values
df1 = df1[
    ["revolutions", "humidity", "vibration"]
].dropna()

# Reseting index after dropping rows
df1 = df1.reset_index(drop=True)

print("Total rows:", len(df1))

Total rows: 109563

In [27]:
# 3. Features and target
X = df1[
    ["revolutions", "humidity"]
]

y = df1["vibration"]

In [44]:
# 4. Chronological split TRAIN / VALIDATION / TEST 
#    60% Train
#    20% Validation
#    20% Test
# =========================================================

n = len(df1)

train_end = int(n * 0.60)
val_end = int(n * 0.80)



X_train = X.iloc[:train_end]
y_train = y.iloc[:train_end]

X_val = X.iloc[train_end:val_end]
y_val = y.iloc[train_end:val_end]


X_test = X.iloc[val_end:]
y_test = y.iloc[val_end:]

print("\nDataset sizes")

print(X_train)
print("=====================================================")
print(X_test)
print("=====================================================")
print(y_train)
print("=====================================================")
print(y_test)

print("Training rows:", len(X_train))
print("Validation rows:", len(X_val))
print("Test rows:", len(X_test))

Dataset sizes
       revolutions  humidity
0           93.744    73.999
1           93.740    73.999
2           93.736    73.998
3           93.732    73.998
4           93.729    73.998
...            ...       ...
67314       41.078    74.130
67315       41.077    74.131
67316       41.076    74.131
67317       41.075    74.131
67318       41.074    74.131

[65737 rows x 2 columns]
=====================================================
        revolutions  humidity
90009        23.656    74.499
90010        23.658    74.499
90011        23.659    74.498
90012        23.661    74.498
90013        23.662    74.498
...             ...       ...
111996       20.186    73.992
111997       20.186    73.992
111998       20.185    73.992
111999       20.185    73.992
112000       20.184    73.992

[21913 rows x 2 columns]
=====================================================
0        18.00
1        18.00
2        18.00
3        18.00
4        18.00
         ...
67314    28.58
67315    28.56
67316     2.86
67317    28.54
67318    28.53
Name: vibration, Length: 65737, dtype: float64
=====================================================
90009     39.96
90010      4.00
90011     39.95
90012      3.99
90013     39.94
          ...
111996     2.00
111997    20.01
111998    20.01
111999    20.00
112000     2.00
Name: vibration, Length: 21913, dtype: float64
Training rows: 65737
Validation rows: 21913
Test rows: 21913

In [29]:
# 5. Train model
model = LinearRegression()

model.fit(
    X_train,
    y_train
)

LinearRegression()

In [40]:
# 6. Predictions
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)
print(train_pred)
print("=================================")
print(test_pred)

[17.19680504 17.19784946 17.19580923 ... 37.04054213 37.04028102
 37.03975881]
=================================
[37.03949771 37.03897549 37.03562974 ... 36.38187912 36.38187912
 36.38214023]

In [31]:
# 7. Training residuals
train_residuals = (
    y_train - train_pred
)

In [39]:
train_residuals

0         0.803195
1         0.802151
2         0.804191
3         0.803146
4         0.802363
           ...
90004   -33.041325
90005     2.938936
90006   -33.040542
90007     2.929719
90008   -33.039759
Name: vibration, Length: 87650, dtype: float64

In [32]:
# 8. Threshold
threshold = (
    train_residuals
    .abs()
    .quantile(0.95)
)

print(
    "Abnormal vibration threshold:",
    threshold
)

Abnormal vibration threshold: 51.82094787626185

In [33]:
# 9. Test results
results = df1.iloc[split_index:].copy()

results["predicted_vibration"] = test_pred

results["residual"] = (
    results["vibration"]
    - results["predicted_vibration"]
)

In [34]:
# 10. Binary threshold feature
results["abnormal_vibration"] = (
    results["residual"].abs()
    > threshold
).astype(int)

In [35]:
# 11. Severity classification
def vibration_status(residual):
    error = abs(residual)

    if error <= threshold:
        return "Normal"

    elif error <= 2 * threshold:
        return "Warning"

    else:
        return "Critical"

results["status"] = (
    results["residual"]
    .apply(vibration_status)
)

In [36]:
# 12. Model evaluation
mae = mean_absolute_error(
    y_test,
    test_pred
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        test_pred
    )
)

r2 = r2_score(
    y_test,
    test_pred
)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 11.721405461806807
RMSE: 17.548238743160233
R2: -0.45389745959118377

In [37]:
# 13. Model equation
print("Intercept:", model.intercept_)

for feature, coefficient in zip(
    X.columns,
    model.coef_
):
    print(
        feature,
        coefficient
    )

# 14. Final results
print(
    results[
        [
            "revolutions",
            "humidity",
            "vibration",
            "predicted_vibration",
            "residual",
            "abnormal_vibration",
            "status"
        ]
    ].head(20)
)

Intercept: -186.5869175108931
revolutions -0.2611055970674097
humidity 3.084647166008193
       revolutions  humidity  vibration  predicted_vibration   residual  \
90009       23.656    74.499      39.96            37.039498   2.920502
90010       23.658    74.499       4.00            37.038975 -33.038975
90011       23.659    74.498      39.95            37.035630   2.914370
90012       23.661    74.498       3.99            37.035108 -33.045108
90013       23.662    74.498      39.94            37.034846   2.905154
90014       23.664    74.498       3.99            37.034324 -33.044324
90015       23.665    74.498      39.93            37.034063   2.895937
90016       23.667    74.498       3.99            37.033541 -33.043541
90017       23.668    74.498      39.92            37.033280   2.886720
90018       23.670    74.498       3.99            37.032758 -33.042758
90019       23.671    74.498      39.91            37.032496   2.877504
90020       23.672    74.498      99.00            37.032235  61.967765
90021       23.674    74.498      39.90            37.031713   2.868287
90022       23.675    74.498       3.99            37.031452 -33.041452
90023       23.677    74.498      39.89            37.030930   2.859070
90024       23.678    74.498       3.99            37.030669 -33.040669
90025       23.680    74.498      39.88            37.030147   2.849853
90026       23.681    74.498       3.99            37.029885 -33.039885
90027       23.683    74.498      39.87            37.029363   2.840637
90028       23.684    74.498       3.99            37.029102 -33.039102

       abnormal_vibration   status
90009                   0   Normal
90010                   0   Normal
90011                   0   Normal
90012                   0   Normal
90013                   0   Normal
90014                   0   Normal
90015                   0   Normal
90016                   0   Normal
90017                   0   Normal
90018                   0   Normal
90019                   0   Normal
90020                   1  Warning
90021                   0   Normal
90022                   0   Normal
90023                   0   Normal
90024                   0   Normal
90025                   0   Normal
90026                   0   Normal
90027                   0   Normal
90028                   0   Normal

In [23]:
results

,revolutions,humidity,vibration,predicted_vibration,residual,abnormal_vibration,status
90009,23.656,74.499,39.96,37.039498,2.920502,0,Normal
90010,23.658,74.499,4.00,37.038975,-33.038975,0,Normal
90011,23.659,74.498,39.95,37.035630,2.914370,0,Normal
90012,23.661,74.498,3.99,37.035108,-33.045108,0,Normal
90013,23.662,74.498,39.94,37.034846,2.905154,0,Normal
...,...,...,...,...,...,...,...
111996,20.186,73.992,2.00,36.381618,-34.381618,0,Normal
111997,20.186,73.992,20.01,36.381618,-16.371618,0,Normal
111998,20.185,73.992,20.01,36.381879,-16.371879,0,Normal
111999,20.185,73.992,20.00,36.381879,-16.381879,0,Normal
112000,20.184,73.992,2.00,36.382140,-34.382140,0,Normal